spring:
  application:
    name: sai-backend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/sai_backend
    username: shinhanuser
    password: 1234

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/user.sql
        - classpath:db/loancontract.sql

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.teamsai.saiwonjang.domain
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

mock-bank:
  base-url: http://localhost:8081

logging:
  level:
    com.teamsai.saiwonjang: debug

jwt:
  secret: 01d0d25e07ba3a7ec20c104e926ade45d26845e5fbba522fff0ec08f43522fa94adbe9a10eb283ad814effbae89a8a0daf0c5e36153416ee855e8d8d1130f650
  access-token-expiration-ms: 3600000

portone:
  identity:
    base-url: https://api.portone.io
    store-id: store-a946d014-1ad1-42ec-8c79-9874b24f7e3e
    channel-key: channel-key-a5f1ce39-964e-465b-9dd1-7077d7b309e6
    api-secret: CwzJtVScIHrC0kblCy7YVuDmYh9tARI2KzZOcUdbY9Qtgq1xNs0hTkPRnm7VEuPI6E2AK4rlgAY1hnx0
    valid-minutes: 10
